# Generated by Django 3.0 on 2022-02-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_address
            SELECT * FROM oc_lettings_site_address;
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_address
            SELECT * FROM lettings_address;
        """)
    ]
