# Generated by Django 3.0 on 2022-02-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20220211_1553'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_letting
            SELECT * FROM oc_lettings_site_letting;
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_letting
            SELECT * FROM lettings_letting;
        """)
    ]

