# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  python: circleci/python@1.1.0
jobs:
  tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - python/install-packages:
          args: flake8
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
            pytest
          name: Test
            
      - run:
          name: linting
          command: |
            flake8
  
  build_docker_push:
    docker:
        - image: cimg/python:3.8
          auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker build -t $CIRCLE_SHA1 .
            docker tag $CIRCLE_SHA1 $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
  
  deployment:
    machine: True
    steps:
      - checkout
      - run:
          name: Push to Heroku and deploy
          command: |              
              set -ex
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
              heroku config:set DJANGO_ALLOWED_HOSTS=$HEROKU_APP_NAME.herokuapp.com --app $HEROKU_APP_NAME
              heroku config:set SECRET_KEY=$HEROKU_SECRET_KEY --app $HEROKU_APP_NAME
              heroku config:set DJANGO_DEBUG=0 --app $HEROKU_APP_NAME
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker pull $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
              docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
              heroku container:release --app=$HEROKU_APP_NAME web

workflows:
  build_tests:
    jobs:
      - tests
      - build_docker_push:
          requires:
            - tests
          filters:
            branches:
              only: 
                - master
      - deployment:
          requires:
            - build_docker_push
          filters:
            branches:
              only: 
                - master

